import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Dimension

    // spacings

    /// 112
    public static let dimensionspacings4Xl = 112 
    public static let dimensionspacings3Xl = 96 
    public static let dimensionspacingsXxl = 64 
    public static let dimensionspacingsXl = 48 
    public static let dimensionspacingsLg = 32 
    public static let dimensionspacingsMd = 24 

    /// 16
    public static let dimensionspacingsSm = 16 

    /// 16
    public static let dimensionspacingsXs = 12 

    /// 4
    public static let dimensionspacingsXxs = 4 
    public static let dimensionspacings3Xs = 8 

    /// 4
    public static let dimensionspacings4Xs = 4 

    /// 4
    public static let dimensionspacings5Xs = 2 

    /// 16
    public static let dimensionspacings2Xs = 10 

    // custom
    public static let dimensionspacingscustomMd = 20 
    public static let dimensionspacingscustomButtonW = 28 
    public static let dimensionspacingscustomButtonH = 10 

    // border

    // width
    public static let dimensionborderwidthThin = 1 
    public static let dimensionborderwidthMedium = 2 
    public static let dimensionborderwidthThick = 4 

    // icon
    public static let dimensionbordericonThin = 1 
    public static let dimensionbordericonMedium = 2 
    public static let dimensionbordericonThick = 4 

    // button
    public static let dimensionborderbuttonThin = 1 
    public static let dimensionborderbuttonMedium = 2 
    public static let dimensionborderbuttonThick = 4 

    // tag
    public static let dimensionbordertagThin = 1 
    public static let dimensionbordertagMedium = 2 
    public static let dimensionbordertagThick = 4 

    // track
    public static let dimensionbordertrackThin = 1 
    public static let dimensionbordertrackMedium = 2 
    public static let dimensionbordertrackThick = 4 

    // field
    public static let dimensionborderfieldThin = 1 
    public static let dimensionborderfieldMedium = 2 
    public static let dimensionborderfieldThick = 4 

    // table
    public static let dimensionbordertableThin = 1 
    public static let dimensionbordertableMedium = 2 
    public static let dimensionbordertableThick = 4 

    // radius
    public static let dimensionradiusNone = 0 
    public static let dimensionradiusM = 8 
    public static let dimensionradiusL = 16 
    public static let dimensionradiusFull = 1000 
    public static let dimensionradiusS = 4 
    public static let dimensionradiusXl = 44 
    public static let dimensionradiusXs = 2 

    // icon
    public static let dimensionradiusiconS = 0 
    public static let dimensionradiusiconM = 8 
    public static let dimensionradiusiconRound = 1000 

    // button
    public static let dimensionradiusbuttonS = 0 
    public static let dimensionradiusbuttonM = 8 
    public static let dimensionradiusbuttonRound = 1000 

    // indicator
    public static let dimensionradiusindicatorS = 4 
    public static let dimensionradiusindicatorM = 8 
    public static let dimensionradiusindicatorRound = 1000 

    // card
    public static let dimensionradiuscardNone = 0 
    public static let dimensionradiuscardM = 8 
    public static let dimensionradiuscardRound = 1000 
    public static let dimensionradiuscardS = 4 

    // field
    public static let dimensionradiusfieldS = 2 
    public static let dimensionradiusfieldM = 8 
    public static let dimensionradiusfieldRound = 1000 
    public static let dimensionradiusfieldL = 44 

    // spacing

    // button
    public static let dimensionspacingbuttonPadding = 20 

    // corner

    // radius
    public static let dimensionspacingcornerradiusS = 4 
    public static let dimensionspacingcornerradiusM = 8 
    public static let dimensionspacingcornerradiusRound = 96 

    // padding
    public static let dimensionspacingpaddingItem4 = 4 
    public static let dimensionspacingpaddingItem8 = 8 
    public static let dimensionspacingpaddingItem16 = 16 
    public static let dimensionspacingpaddingItem24 = 24 
    public static let dimensionspacingpaddingItem32 = 32 
    public static let dimensionspacingpaddingItem48 = 48 
    public static let dimensionspacingpaddingItem64 = 64 
    public static let dimensionspacingpaddingItem12 = 12 
    public static let dimensionspacingpaddingItem2 = 2 
    public static let dimensionspacingpaddingItem10 = 10 

    // spacing
    public static let dimensionspacingspacingItem4 = 4 
    public static let dimensionspacingspacingItem8 = 8 
    public static let dimensionspacingspacingItem16 = 16 
    public static let dimensionspacingspacingItem24 = 24 
    public static let dimensionspacingspacingItem32 = 32 
    public static let dimensionspacingspacingItem48 = 48 
    public static let dimensionspacingspacingItem64 = 64 
    public static let dimensionspacingspacingItem2 = 2 

    // data-table
    public static let dimensiondataTableCellPaddingBlockFigmaOnly = 8 
    public static let dimensiondataTableHeaderPaddingBlockFigmaOnly = 12 

    // font

    // size
    public static let dimensionfontsize4Xl = 48 
    public static let dimensionfontsize3Xl = 40 
    public static let dimensionfontsize2Xl = 32 
    public static let dimensionfontsizeXl = 24 
    public static let dimensionfontsizeL = 20 
    public static let dimensionfontsizeS = 16 
    public static let dimensionfontsizeXs = 14 
    public static let dimensionfontsize4Xs = 10 
    public static let dimensionfontsize5Xl = 60 
    public static let dimensionfontsize6Xl = 80 
    public static let dimensionfontsize2Xs = 12 
    public static let dimensionfontsize3Xs = 11 
    public static let dimensionfontsizeM = 17 

    // line-height
    public static let dimensionfontlineHeight3Xl = 42 
    public static let dimensionfontlineHeight2Xl = 38 
    public static let dimensionfontlineHeightM = 32 
    public static let dimensionfontlineHeightXs = 24 
    public static let dimensionfontlineHeight3Xs = 20 
    public static let dimensionfontlineHeight5Xs = 16 
    public static let dimensionfontlineHeight4Xl = 44 
    public static let dimensionfontlineHeight5Xl = 52 
    public static let dimensionfontlineHeight6Xl = 60 
    public static let dimensionfontlineHeight7Xl = 74 
    public static let dimensionfontlineHeightL = 36 
    public static let dimensionfontlineHeightS = 28 
    public static let dimensionfontlineHeight6Xs = 10 
    public static let dimensionfontlineHeight2Xs = 22 
    public static let dimensionfontlineHeight4Xs = 18 

    // letter-spacing
    public static let dimensionfontletterSpacingRegular = 0 
    public static let dimensionfontletterSpacingWide = 0.5 
    public static let dimensionfontletterSpacingTight = -0.5 
}