import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        // Fuschia
        public let fuschia100 = Color(.sRGB, red: 239/255, green: 93/255, blue: 168/255, opacity: 1) 
        public let fuschia80 = Color(.sRGB, red: 241/255, green: 120/255, blue: 182/255, opacity: 1) 
        public let fuschia60 = Color(.sRGB, red: 252/255, green: 221/255, blue: 236/255, opacity: 1) 

        // Iris
        public let iris100 = Color(.sRGB, red: 93/255, green: 95/255, blue: 239/255, opacity: 1) 
        public let iris80 = Color(.sRGB, red: 120/255, green: 121/255, blue: 241/255, opacity: 1) 
        public let iris60 = Color(.sRGB, red: 165/255, green: 166/255, blue: 246/255, opacity: 1) 
    }
}