import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    func textStyleHeader1() -> some View {
        return self
            .font(Font.custom("Work Sans-700", size: 34))
    }

    func textStyleHeader2() -> some View {
        return self
            .font(Font.custom("Work Sans-700", size: 20))
    }

    func textStyleBody() -> some View {
        return self
            .font(Font.custom("Work Sans-400", size: 13))
    }
}
